### ISSUE TITLE
Проблема с impack плагином

### ISSUE THREAD

**Issue by MiaSoftCCode** [Leonid-Ganin/CCode#4]
Дропает ошибку
Без него:
![image](https://user-images.githubusercontent.com/120322215/206910987-a75f1f6e-5559-496b-8184-2917adb4d462.png)
С ним:
![image](https://user-images.githubusercontent.com/120322215/206911042-bfdcbd51-cee2-4e82-a29a-e7bda74b0acd.png)

**Comment by Leonid-Ganin** [comment]
Перейди по этому пути: %appdata%\Corona Labs\Corona Simulator\Plugins
Удали оттуда всё и распакуй данный архив:
[Plugins.zip](https://github.com/Leonid-Ganin/CCode/files/10202602/Plugins.zip)

**Comment by MiaSoftCCode** [comment]
Не, всё равно дропает.

**Comment by MiaSoftCCode** [comment]
@Leonid-Ganin, лечится только
![image](https://user-images.githubusercontent.com/120322215/206917218-567dbb32-7a94-43bf-aad1-acf6fb2025d1.png)

**Comment by Leonid-Ganin** [comment]
У меня всё отлично, и при сборке тоже всё ок, не знаю, у тебя какая ось?

**Comment by MiaSoftCCode** [comment]
11-ая. при сборке тоже выдает бэбэну.

**Comment by MiaSoftCCode** [comment]
![image](https://user-images.githubusercontent.com/120322215/206917959-cec5c860-5a8a-496f-8f66-8daf48968073.png)
Ошибка при сборке в апк файл через file->build->android.

**Comment by Leonid-Ganin** [comment]
Ну может это траблы 11 винды, у меня на 10 работает и Даня на 10 тоже не жаловался, закрываю проблему
